### ISSUE TITLE
edge在chrome插件商店安装的插件,在chrome插件商店页面点击插件图标显示"请刷新Tab页面",在github页面点击插件图标显示"无数据",在其他页面正常

### ISSUE THREAD

**Issue by RiotGamesU** [fofapro/fofa_view#10]

**Comment by 0nise** [comment]
问题是出现在 edge 浏览器吗？

**Comment by RiotGamesU** [comment]
> 问题是出现在 edge 浏览器吗？

是的,chrome和edge商店页面,一些敏感站点以及本地或非站点(例如浏览器设置页面等)等点击插件图标都会直接显示"请刷新Tab页面",github页面点击插件图标会显示一会加载动画,然后显示端口80,协议http,其他项都为空
