### ISSUE TITLE
是否能够提供更新

### ISSUE THREAD

**Issue by Micheai** [fofapro/fofa_view#11]
FOFA Pro view近期经常获取不到资产信息 是否能够提供更新

**Comment by 0nise** [comment]
进去发获取资产是因为FOFA改版导致的，会在最近解决该问题发布新版。

**Comment by xxxxbxxxxx** [comment]
新版本已发布，可通过 https://github.com/fofapro/fofa_view/releases 下载，也可通过浏览器应用商店安装更新（可能会延迟，大致1～2天）。
