### ISSUE TITLE
新增功能添加建议

### ISSUE THREAD

**Issue by sinlee1** [fofapro/fofa_view#7]
- 建议FOFA网络空间测绘添加漏洞扫描的功能，类似效果如下图所示

![image](https://user-images.githubusercontent.com/29684167/87520785-02b53900-c6b6-11ea-9fe5-001040b0fba9.png)

**Comment by 0nise** [comment]
插件是无法支持漏洞探测功能的。

**Comment by sinlee1** [comment]
并不是指的插件，而是指的fofa.so的官网，可以添加这个功能。

**Comment by 0nise** [comment]
这个功能内部已经反馈了，在排期中。

**Comment by sinlee1** [comment]
大佬优秀，早点休息。

**Comment by 0nise** [comment]
有想法可以反馈在这里
